# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
jobs: 
    - job: BuildDocker
      displayName: Build Docker
      steps:
      - script: |
          # --publish-all because I need a random port
          echo ${PWD}
          python -m pip install -r requirements.txt
          echo Install done! 
          ls
          python tests/run_fairseq_tests.py
          echo tests done! 
          echo ${PWD}
        name: UnitTests