# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

#Azure pipeline for continuous integration

trigger:
  paths:
    exclude:
      - docs      
jobs:
  - job: Fastseq_unittests
    timeoutInMinutes: 360
    pool: 
      name: default
      demands:
        - agent.name -equals gpu0 
    steps:
    - script: |
        #set up docker
        sudo docker run --gpus all --privileged  -it adsbrainwestus2.azurecr.io/fastseq:dev-py3 /bin/bash
        #install fastseq
        pip install --editable .
        
        #show environment
        which python
        python --version
        nvcc --version
        python -c "import torch; print('torch:', torch.__version__, torch)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
         
        export CUDA_VISIBLE_DEVICES=3
        echo "******* Running fairseq unittests *******"
        bash tests/run_fairseq_tests.sh
        echo "******* Running transformers unittests *******"
        bash tests/run_transformers_tests.sh
        echo "******* Running fastseq unittests *******"
        python -m unittest discover -s tests/ -p 'test_*.py' -v
        #cd benchmarks/
        #CUDA_VISIBLE_DEVICES=3 run_all_benchmarks.sh
      displayName: 'setup environment and run fastseq unit tests'  
