# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
jobs: 
    - job: BuildDocker
      displayName: Build Docker
      steps:
      - script: |
          # --publish-all because I need a random port
          sudo docker run --gpus all --privileged  -it adsbrainwestus2.azurecr.io/prophetnet:20.03-py3 /bin/bash
          echo ${PWD}
          cd fastseq
          python -m pip install -r requirements.txt
          python tests/run_fairseq_tests.py
          echo ${PWD}
        name: UnitTests