#
trigger:
  paths:
    exclude:
      - docs      
jobs:
  - job: Fastseq_Tests
    timeoutInMinutes: 360
    pool: 
      name: default
      demands:
        - agent.name -equals gpu4 

    steps:
    - script: |
        sudo docker run --gpus all  --network=host --privileged -w '/root'  --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864  adsbrainwestus2.azurecr.io/fastseq:dev-py3 /bin/bash
        pip install --editable .
        bash tests/run_fairseq_tests.sh
      displayName: 'Setup environment and run fairseq tests'

  
